<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/commands/replace_cpp_function.hpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
//&nbsp;#pragma&nbsp;once<br>
//&nbsp;#include&nbsp;&quot;command_base.hpp&quot;<br>
//&nbsp;#include&nbsp;&quot;commands/symbol_utils.h&quot;<br>
//&nbsp;#include&nbsp;&quot;languages/symbols.h&quot;<br>
<br>
//&nbsp;class&nbsp;ReplaceCppFunctionCommand&nbsp;:&nbsp;public&nbsp;RegionReplaceCommand<br>
//&nbsp;{<br>
//&nbsp;public:<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ReplaceCppFunctionCommand()<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;RegionReplaceCommand(&quot;replace-cpp-function&quot;)<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;parse(const&nbsp;nos::trent&nbsp;&amp;tr)&nbsp;override<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RegionReplaceCommand::parse(tr);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;function_text&nbsp;=&nbsp;command_parse::get_scalar(tr,&nbsp;&quot;function&quot;);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;symbol_text&nbsp;=&nbsp;command_parse::get_scalar(tr,&nbsp;&quot;symbol&quot;);<br>
<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!function_text.empty())<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target_&nbsp;=&nbsp;function_text;<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(!symbol_text.empty())<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target_&nbsp;=&nbsp;symbol_text;<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;YAML&nbsp;patch:&nbsp;op&nbsp;'&quot;&nbsp;+&nbsp;command_name()&nbsp;+<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;'&nbsp;requires&nbsp;'function'&nbsp;or&nbsp;'symbol'&quot;);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(target_.empty())<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-cpp-function:&nbsp;empty&nbsp;function&nbsp;name&quot;);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
//&nbsp;protected:<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_region(const&nbsp;std::string&nbsp;&amp;text,&nbsp;Region&nbsp;&amp;r)&nbsp;const&nbsp;override<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CppSymbolFinder&nbsp;finder(text);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;finder.find_function(target_,&nbsp;r);<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;not_found_error()&nbsp;const&nbsp;override<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;replace-cpp-function:&nbsp;function&nbsp;not&nbsp;found:&nbsp;&quot;&nbsp;+&nbsp;target_&nbsp;+<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;in&nbsp;file:&nbsp;&quot;&nbsp;+&nbsp;filepath_;<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;invalid_region_error()&nbsp;const&nbsp;override<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;replace-cpp-function:&nbsp;invalid&nbsp;region&quot;;<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
//&nbsp;private:<br>
//&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;target_;<br>
//&nbsp;};<br>
<!-- END SCAT CODE -->
</body>
</html>
