<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/command_fabric.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;command_fabric.h&quot;<br>
#include&nbsp;&quot;commands/append_text.hpp&quot;<br>
#include&nbsp;&quot;commands/create_file.hpp&quot;<br>
#include&nbsp;&quot;commands/delete_file.hpp&quot;<br>
#include&nbsp;&quot;commands/delete_text.hpp&quot;<br>
#include&nbsp;&quot;commands/insert_after_text.hpp&quot;<br>
#include&nbsp;&quot;commands/insert_before_text.hpp&quot;<br>
#include&nbsp;&quot;commands/prepend_text.hpp&quot;<br>
#include&nbsp;&quot;commands/replace_cpp_class.hpp&quot;<br>
#include&nbsp;&quot;commands/replace_cpp_method.hpp&quot;<br>
#include&nbsp;&quot;commands/replace_py_class.hpp&quot;<br>
#include&nbsp;&quot;commands/replace_py_method.hpp&quot;<br>
#include&nbsp;&quot;commands/replace_text.hpp&quot;<br>
#include&nbsp;&lt;functional&gt;<br>
#include&nbsp;&lt;unordered_map&gt;<br>
<br>
namespace&nbsp;commands_detail<br>
{<br>
using&nbsp;CommandFactory&nbsp;=&nbsp;std::function&lt;std::unique_ptr&lt;Command&gt;()&gt;;<br>
}<br>
<br>
const&nbsp;std::unordered_map&lt;std::string,&nbsp;commands_detail::CommandFactory&gt;&nbsp;&amp;<br>
symbol_command_registry()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;using&nbsp;namespace&nbsp;commands_detail;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;const&nbsp;std::unordered_map&lt;std::string,&nbsp;CommandFactory&gt;&nbsp;registry&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-cpp-class&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;ReplaceCppClassCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-cpp-method&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;ReplaceCppMethodCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-py-class&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;ReplacePyClassCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-py-method&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;ReplacePyMethodCommand&gt;();&nbsp;}},<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;prepend-text&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;PrependTextCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;append-text&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;AppendTextCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;insert-after-text&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;InsertAfterTextCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;insert-before-text&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;InsertBeforeTextCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-text&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;ReplaceTextCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;delete-text&quot;,&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;DeleteTextCommand&gt;();&nbsp;}},<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;create-file&quot;,&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;CreateFileCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&quot;delete-file&quot;,&nbsp;[]()&nbsp;{&nbsp;return&nbsp;std::make_unique&lt;DeleteFileCommand&gt;();&nbsp;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;registry;<br>
}<br>
<br>
std::unique_ptr&lt;Command&gt;&nbsp;make_command(const&nbsp;std::string&nbsp;&amp;name)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;auto&nbsp;&amp;registry&nbsp;=&nbsp;symbol_command_registry();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;registry.find(name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it&nbsp;==&nbsp;registry.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;YAML&nbsp;patch:&nbsp;unknown&nbsp;operation:&nbsp;&quot;&nbsp;+&nbsp;name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;it-&gt;second();<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
