<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/command.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;command.h&quot;<br>
#include&nbsp;&lt;exception&gt;<br>
<br>
#include&nbsp;&lt;ostream&gt;<br>
<br>
Command::Command(std::string&nbsp;name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;name_(std::move(name))<br>
{<br>
}<br>
<br>
void&nbsp;Command::reset_status()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::NotRun;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_.clear();<br>
}<br>
<br>
void&nbsp;Command::mark_success()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::Success;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_.clear();<br>
}<br>
<br>
void&nbsp;Command::mark_failed(const&nbsp;std::string&nbsp;&amp;message)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::Failed;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_&nbsp;=&nbsp;message;<br>
}<br>
<br>
void&nbsp;Command::run(std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;reset_status();<br>
&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;execute(lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_success();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;std::exception&nbsp;&amp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_failed(e.what());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(...)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_failed(&quot;unknown&nbsp;error&nbsp;while&nbsp;executing&nbsp;command&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
void&nbsp;Command::append_debug_info(std::ostream&nbsp;&amp;)&nbsp;const<br>
{<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
