<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/command.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;command.h&quot;<br>
#include&nbsp;&lt;exception&gt;<br>
<br>
#include&nbsp;&lt;ostream&gt;<br>
<br>
Command::Command(std::string&nbsp;name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;name_(std::move(name))<br>
{<br>
}<br>
<br>
void&nbsp;Command::reset_status()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::NotRun;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_.clear();<br>
}<br>
<br>
void&nbsp;Command::mark_success()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::Success;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_.clear();<br>
}<br>
<br>
void&nbsp;Command::mark_failed(const&nbsp;std::string&nbsp;&amp;message)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::Failed;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_&nbsp;=&nbsp;message;<br>
}<br>
<br>
std::size_t&nbsp;Command::count_total_chars(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;total&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(lines.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;ln&nbsp;:&nbsp;lines)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total&nbsp;+=&nbsp;ln.size()&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;total;<br>
}<br>
<br>
void&nbsp;Command::record_effect(std::size_t&nbsp;before_size,&nbsp;std::size_t&nbsp;after_size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(after_size&nbsp;&gt;=&nbsp;before_size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_inserted_&nbsp;=&nbsp;after_size&nbsp;-&nbsp;before_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_removed_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_inserted_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_removed_&nbsp;=&nbsp;before_size&nbsp;-&nbsp;after_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;Command::record_effect(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;before,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;after)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;сначала&nbsp;считаем&nbsp;байты,&nbsp;как&nbsp;и&nbsp;раньше<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;before_size&nbsp;=&nbsp;count_total_chars(before);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;after_size&nbsp;=&nbsp;count_total_chars(after);<br>
&nbsp;&nbsp;&nbsp;&nbsp;record_effect(before_size,&nbsp;after_size);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;затем&nbsp;считаем&nbsp;изменение&nbsp;по&nbsp;строкам&nbsp;и&nbsp;диапазон<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines_inserted_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines_removed_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;has_effect_region_&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;effect_start_line_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;effect_end_line_&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::size_t&nbsp;before_lines&nbsp;=&nbsp;before.size();<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::size_t&nbsp;after_lines&nbsp;=&nbsp;after.size();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;equal&nbsp;=&nbsp;(before_lines&nbsp;==&nbsp;after_lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(equal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(std::size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;before_lines;&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(before[i]&nbsp;!=&nbsp;after[i])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;equal&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(equal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;prefix&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(prefix&nbsp;&lt;&nbsp;before_lines&nbsp;&amp;&amp;&nbsp;prefix&nbsp;&lt;&nbsp;after_lines&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;before[prefix]&nbsp;==&nbsp;after[prefix])<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++prefix;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;suffix&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(suffix&nbsp;&lt;&nbsp;before_lines&nbsp;-&nbsp;prefix&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;suffix&nbsp;&lt;&nbsp;after_lines&nbsp;-&nbsp;prefix&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;before[before_lines&nbsp;-&nbsp;1&nbsp;-&nbsp;suffix]&nbsp;==&nbsp;after[after_lines&nbsp;-&nbsp;1&nbsp;-&nbsp;suffix])<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++suffix;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;before_changed_start&nbsp;=&nbsp;prefix;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;before_changed_end&nbsp;=&nbsp;before_lines&nbsp;-&nbsp;suffix;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;after_changed_start&nbsp;=&nbsp;prefix;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;after_changed_end&nbsp;=&nbsp;after_lines&nbsp;-&nbsp;suffix;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(before_changed_start&nbsp;&gt;&nbsp;before_changed_end)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;before_changed_start&nbsp;=&nbsp;before_changed_end;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(after_changed_start&nbsp;&gt;&nbsp;after_changed_end)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;after_changed_start&nbsp;=&nbsp;after_changed_end;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(before_changed_end&nbsp;&gt;&nbsp;before_changed_start)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lines_removed_&nbsp;=&nbsp;before_changed_end&nbsp;-&nbsp;before_changed_start;<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lines_removed_&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(after_changed_end&nbsp;&gt;&nbsp;after_changed_start)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lines_inserted_&nbsp;=&nbsp;after_changed_end&nbsp;-&nbsp;after_changed_start;<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lines_inserted_&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(lines_inserted_&nbsp;==&nbsp;0&nbsp;&amp;&amp;&nbsp;lines_removed_&nbsp;==&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;has_effect_region_&nbsp;=&nbsp;true;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(lines_removed_&nbsp;&gt;&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;effect_start_line_&nbsp;=&nbsp;before_changed_start&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;effect_end_line_&nbsp;=&nbsp;before_changed_end;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(effect_end_line_&nbsp;&lt;&nbsp;effect_start_line_)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;effect_end_line_&nbsp;=&nbsp;effect_start_line_;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;effect_start_line_&nbsp;=&nbsp;after_changed_start&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;effect_end_line_&nbsp;=&nbsp;effect_start_line_;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;Command::run(std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;reset_status();<br>
&nbsp;&nbsp;&nbsp;&nbsp;chars_inserted_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;chars_removed_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines_inserted_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines_removed_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;has_effect_region_&nbsp;=&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;effect_start_line_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;effect_end_line_&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;before&nbsp;=&nbsp;lines;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;execute(lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;record_effect(before,&nbsp;lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_success();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;std::exception&nbsp;&amp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_failed(e.what());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(...)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_failed(&quot;unknown&nbsp;error&nbsp;while&nbsp;executing&nbsp;command&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
void&nbsp;Command::append_debug_info(std::ostream&nbsp;&amp;)&nbsp;const<br>
{<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
