<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/command.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;command.h&quot;<br>
#include&nbsp;&lt;exception&gt;<br>
<br>
#include&nbsp;&lt;ostream&gt;<br>
<br>
Command::Command(std::string&nbsp;name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;name_(std::move(name))<br>
{<br>
}<br>
<br>
void&nbsp;Command::reset_status()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::NotRun;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_.clear();<br>
}<br>
<br>
void&nbsp;Command::mark_success()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::Success;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_.clear();<br>
}<br>
<br>
void&nbsp;Command::mark_failed(const&nbsp;std::string&nbsp;&amp;message)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;status_&nbsp;=&nbsp;Status::Failed;<br>
&nbsp;&nbsp;&nbsp;&nbsp;error_message_&nbsp;=&nbsp;message;<br>
}<br>
<br>
std::size_t&nbsp;Command::count_total_chars(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;total&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(lines.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;ln&nbsp;:&nbsp;lines)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total&nbsp;+=&nbsp;ln.size()&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;total;<br>
}<br>
<br>
void&nbsp;Command::record_effect(std::size_t&nbsp;before_size,&nbsp;std::size_t&nbsp;after_size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(after_size&nbsp;&gt;=&nbsp;before_size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_inserted_&nbsp;=&nbsp;after_size&nbsp;-&nbsp;before_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_removed_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_inserted_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chars_removed_&nbsp;=&nbsp;before_size&nbsp;-&nbsp;after_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;Command::run(std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;reset_status();<br>
&nbsp;&nbsp;&nbsp;&nbsp;chars_inserted_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;chars_removed_&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;before_size&nbsp;=&nbsp;count_total_chars(lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;execute(lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;after_size&nbsp;=&nbsp;count_total_chars(lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;record_effect(before_size,&nbsp;after_size);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_success();<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;std::exception&nbsp;&amp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_failed(e.what());<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(...)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mark_failed(&quot;unknown&nbsp;error&nbsp;while&nbsp;executing&nbsp;command&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
void&nbsp;Command::append_debug_info(std::ostream&nbsp;&amp;)&nbsp;const<br>
{<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
