<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/file_command_objects.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;file_command_objects.h&quot;<br>
<br>
#include&nbsp;&quot;command_parse_helpers.h&quot;<br>
#include&nbsp;&quot;file_io.h&quot;<br>
<br>
#include&nbsp;&lt;stdexcept&gt;<br>
<br>
using&nbsp;command_parse::get_scalar;<br>
using&nbsp;command_parse::split_scalar_lines;<br>
<br>
CreateFileCommand::CreateFileCommand()&nbsp;:&nbsp;Command(&quot;create-file&quot;)&nbsp;{}<br>
<br>
void&nbsp;CreateFileCommand::parse(const&nbsp;nos::trent&nbsp;&amp;tr)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;section_.filepath&nbsp;=&nbsp;get_scalar(tr,&nbsp;&quot;path&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(section_.filepath.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;YAML&nbsp;patch:&nbsp;op&nbsp;'create-file'&nbsp;requires&nbsp;'path'&nbsp;key&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;section_.payload&nbsp;=&nbsp;split_scalar_lines(get_scalar(tr,&nbsp;&quot;payload&quot;));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;section_.comment&nbsp;=&nbsp;get_scalar(tr,&nbsp;&quot;comment&quot;);<br>
}<br>
<br>
void&nbsp;CreateFileCommand::execute(std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)lines;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::filesystem::path&nbsp;p(section_.filepath);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(std::filesystem::exists(p))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;write_file_lines(p,&nbsp;section_.payload);<br>
}<br>
<br>
DeleteFileCommand::DeleteFileCommand()&nbsp;:&nbsp;Command(&quot;delete-file&quot;)&nbsp;{}<br>
<br>
void&nbsp;DeleteFileCommand::parse(const&nbsp;nos::trent&nbsp;&amp;tr)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;section_.filepath&nbsp;=&nbsp;get_scalar(tr,&nbsp;&quot;path&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(section_.filepath.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;YAML&nbsp;patch:&nbsp;op&nbsp;'delete-file'&nbsp;requires&nbsp;'path'&nbsp;key&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;section_.comment&nbsp;=&nbsp;get_scalar(tr,&nbsp;&quot;comment&quot;);<br>
}<br>
<br>
void&nbsp;DeleteFileCommand::execute(std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;(void)lines;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::filesystem::path&nbsp;p(section_.filepath);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!std::filesystem::exists(p))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::error_code&nbsp;ec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::filesystem::remove(p,&nbsp;ec);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(ec)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;delete-file:&nbsp;cannot&nbsp;delete&nbsp;file:&nbsp;&quot;&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;section_.filepath&nbsp;+&nbsp;&quot;:&nbsp;&quot;&nbsp;+&nbsp;ec.message());<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
