<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/parser.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;parser.h&quot;<br>
<br>
#include&nbsp;&quot;command.h&quot;<br>
#include&nbsp;&quot;command_fabric.h&quot;<br>
<br>
#include&nbsp;&lt;memory&gt;<br>
#include&nbsp;&lt;stdexcept&gt;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;yaml/yaml.h&gt;<br>
<br>
using&nbsp;nos::trent;<br>
<br>
static&nbsp;std::unordered_map&lt;std::string,&nbsp;std::vector&lt;std::string&gt;&gt;&nbsp;synonyms&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;insert-after-text&quot;,&nbsp;{&quot;insert-after-text&quot;,&nbsp;&quot;insert-text-after&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;insert-before-text&quot;,&nbsp;{&quot;insert-before-text&quot;,&nbsp;&quot;insert-text-before&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-text&quot;,&nbsp;{&quot;replace-text&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;delete-text&quot;,&nbsp;{&quot;delete-text&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;prepend-text&quot;,&nbsp;{&quot;prepend-text&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;append-text&quot;,&nbsp;{&quot;append-text&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;create-file&quot;,&nbsp;{&quot;create-file&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;delete-file&quot;,&nbsp;{&quot;delete-file&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-cpp-class&quot;,&nbsp;{&quot;replace-cpp-class&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-cpp-method&quot;,&nbsp;{&quot;replace-cpp-method&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-cpp-method&quot;,&nbsp;{&quot;replace-cpp-method&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-cpp-function&quot;,&nbsp;{&quot;replace-cpp-function&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-py-class&quot;,&nbsp;{&quot;replace-py-class&quot;}},<br>
&nbsp;&nbsp;&nbsp;&nbsp;{&quot;replace-py-method&quot;,&nbsp;{&quot;replace-py-method&quot;}},<br>
};<br>
<br>
static&nbsp;std::unordered_map&lt;std::string,&nbsp;std::string&gt;&nbsp;synonym_map;<br>
<br>
namespace<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;ensure_synonym_map()<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!synonym_map.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;pair&nbsp;:&nbsp;synonyms)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;canonical&nbsp;=&nbsp;pair.first;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;std::string&nbsp;&amp;syn&nbsp;:&nbsp;pair.second)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;synonym_map[syn]&nbsp;=&nbsp;canonical;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;normalize_op_name(const&nbsp;std::string&nbsp;&amp;op_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ensure_synonym_map();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;name&nbsp;=&nbsp;op_name;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(char&nbsp;&amp;ch&nbsp;:&nbsp;name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(ch&nbsp;==&nbsp;'_')<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ch&nbsp;=&nbsp;'-';<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;synonym_map.find(name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it&nbsp;==&nbsp;synonym_map.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;YAML&nbsp;patch:&nbsp;unknown&nbsp;operation:&nbsp;&quot;&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;op_name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;it-&gt;second;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}&nbsp;//&nbsp;namespace<br>
<br>
std::vector&lt;std::unique_ptr&lt;Command&gt;&gt;<br>
parse_yaml_patch_text(const&nbsp;std::string&nbsp;&amp;text)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(text);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;patch_language;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*ops_node&nbsp;=&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(root.is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it_lang&nbsp;=&nbsp;dict.find(&quot;language&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it_lang&nbsp;!=&nbsp;dict.end()&nbsp;&amp;&amp;&nbsp;!it_lang-&gt;second.is_nil())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;patch_language&nbsp;=&nbsp;it_lang-&gt;second.as_string();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;dict.find(&quot;operations&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it&nbsp;==&nbsp;dict.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;YAML&nbsp;patch:&nbsp;missing&nbsp;'operations'&nbsp;key&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ops_node&nbsp;=&nbsp;&amp;it-&gt;second;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else&nbsp;if&nbsp;(root.is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ops_node&nbsp;=&nbsp;&amp;root;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;YAML&nbsp;patch:&nbsp;root&nbsp;must&nbsp;be&nbsp;mapping&nbsp;or&nbsp;sequence&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!ops_node-&gt;is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;YAML&nbsp;patch:&nbsp;'operations'&nbsp;must&nbsp;be&nbsp;a&nbsp;sequence&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;auto&nbsp;&amp;ops&nbsp;=&nbsp;ops_node-&gt;as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::unique_ptr&lt;Command&gt;&gt;&nbsp;commands;<br>
&nbsp;&nbsp;&nbsp;&nbsp;commands.reserve(ops.size());<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;trent&nbsp;&amp;op_node&nbsp;:&nbsp;ops)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!op_node.is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;YAML&nbsp;patch:&nbsp;each&nbsp;operation&nbsp;must&nbsp;be&nbsp;a&nbsp;mapping&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;auto&nbsp;&amp;m&nbsp;=&nbsp;op_node.as_dict();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it_op&nbsp;=&nbsp;m.find(&quot;op&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it_op&nbsp;==&nbsp;m.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;YAML&nbsp;patch:&nbsp;operation&nbsp;missing&nbsp;'op'&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;op_name&nbsp;=&nbsp;normalize_op_name(it_op-&gt;second.as_string());<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;cmd&nbsp;=&nbsp;make_command(op_name);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd-&gt;set_patch_language(patch_language);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd-&gt;parse(op_node);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commands.emplace_back(std::move(cmd));<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;commands;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
