<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/symbol_commands.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;symbol_commands.h&quot;<br>
<br>
#include&nbsp;&quot;symbols.h&quot;<br>
<br>
#include&nbsp;&lt;stdexcept&gt;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;utility&gt;<br>
<br>
namespace<br>
{<br>
std::string&nbsp;extract_indent_prefix(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;index)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(index&nbsp;&lt;&nbsp;0&nbsp;||&nbsp;index&nbsp;&gt;=&nbsp;static_cast&lt;int&gt;(lines.size()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;line&nbsp;=&nbsp;lines[static_cast&lt;std::size_t&gt;(index)];<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;j&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(j&nbsp;&lt;&nbsp;line.size()&nbsp;&amp;&amp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(line[j]&nbsp;==&nbsp;'&nbsp;'&nbsp;||&nbsp;line[j]&nbsp;==&nbsp;'\t'))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++j;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;std::string(line,&nbsp;0,&nbsp;j);<br>
}<br>
<br>
std::vector&lt;std::string&gt;<br>
apply_indent_prefix(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;payload,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;prefix,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;enabled)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!enabled&nbsp;||&nbsp;prefix.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;payload;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;result;<br>
&nbsp;&nbsp;&nbsp;&nbsp;result.reserve(payload.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;ln&nbsp;:&nbsp;payload)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(ln.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.push_back(ln);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.push_back(prefix&nbsp;+&nbsp;ln);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result;<br>
}<br>
<br>
std::string&nbsp;join_lines(const&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(lines.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;std::string();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;text;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::size_t&nbsp;total&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;s&nbsp;:&nbsp;lines)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total&nbsp;+=&nbsp;s.size()&nbsp;+&nbsp;1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;text.reserve(total);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(std::size_t&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;lines.size();&nbsp;++i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text&nbsp;+=&nbsp;lines[i];<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(i&nbsp;+&nbsp;1&nbsp;&lt;&nbsp;lines.size())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text&nbsp;+=&nbsp;'\n';<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;text;<br>
}<br>
<br>
std::pair&lt;std::string,&nbsp;std::string&gt;&nbsp;parse_cpp_target(const&nbsp;Section&nbsp;&amp;s)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!s.arg2.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{s.arg1,&nbsp;s.arg2};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;pos&nbsp;=&nbsp;s.arg1.find(&quot;::&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pos&nbsp;==&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-cpp-method:&nbsp;expected&nbsp;'Class::method'&nbsp;or&nbsp;'Class&nbsp;method'&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;cls&nbsp;=&nbsp;s.arg1.substr(0,&nbsp;pos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;method&nbsp;=&nbsp;s.arg1.substr(pos&nbsp;+&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(cls.empty()&nbsp;||&nbsp;method.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-cpp-method:&nbsp;empty&nbsp;class&nbsp;or&nbsp;method&nbsp;name&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{cls,&nbsp;method};<br>
}<br>
<br>
std::pair&lt;std::string,&nbsp;std::string&gt;&nbsp;parse_python_target(const&nbsp;Section&nbsp;&amp;s)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!s.arg2.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{s.arg1,&nbsp;s.arg2};<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;pos&nbsp;=&nbsp;s.arg1.find('.');<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pos&nbsp;==&nbsp;std::string::npos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-py-method:&nbsp;expected&nbsp;'Class.method'&nbsp;or&nbsp;'Class&nbsp;method'&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;cls&nbsp;=&nbsp;s.arg1.substr(0,&nbsp;pos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;method&nbsp;=&nbsp;s.arg1.substr(pos&nbsp;+&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(cls.empty()&nbsp;||&nbsp;method.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-py-method:&nbsp;empty&nbsp;class&nbsp;or&nbsp;method&nbsp;name&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{cls,&nbsp;method};<br>
}<br>
<br>
void&nbsp;replace_cpp_class(const&nbsp;Section&nbsp;&amp;s,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;filepath,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;text,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(s.arg1.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-cpp-class:&nbsp;missing&nbsp;class&nbsp;name&nbsp;for&nbsp;file:&nbsp;&quot;&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filepath);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CppSymbolFinder&nbsp;finder(text);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!finder.find_class(s.arg1,&nbsp;r))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-cpp-class:&nbsp;class&nbsp;not&nbsp;found:&nbsp;&quot;&nbsp;+&nbsp;s.arg1&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;in&nbsp;file:&nbsp;&quot;&nbsp;+&nbsp;filepath);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(r.start_line&nbsp;&lt;&nbsp;0&nbsp;||&nbsp;r.end_line&nbsp;&lt;&nbsp;r.start_line&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r.end_line&nbsp;&gt;=&nbsp;static_cast&lt;int&gt;(lines.size()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;replace-cpp-class:&nbsp;invalid&nbsp;region&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;begin&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;r.start_line;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;end&nbsp;&nbsp;&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;(r.end_line&nbsp;+&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;prefix&nbsp;=&nbsp;extract_indent_prefix(lines,&nbsp;r.start_line);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;payload&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;apply_indent_prefix(s.payload,&nbsp;prefix,&nbsp;s.indent_from_marker);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.erase(begin,&nbsp;end);<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.insert(lines.begin()&nbsp;+&nbsp;r.start_line,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.begin(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.end());<br>
}<br>
<br>
void&nbsp;replace_cpp_method(const&nbsp;Section&nbsp;&amp;s,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;filepath,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;text,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;[cls,&nbsp;method]&nbsp;=&nbsp;parse_cpp_target(s);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CppSymbolFinder&nbsp;finder(text);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!finder.find_method(cls,&nbsp;method,&nbsp;r))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-cpp-method:&nbsp;method&nbsp;not&nbsp;found:&nbsp;&quot;&nbsp;+&nbsp;cls&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;::&quot;&nbsp;+&nbsp;method&nbsp;+&nbsp;&quot;&nbsp;in&nbsp;file:&nbsp;&quot;&nbsp;+&nbsp;filepath);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(r.start_line&nbsp;&lt;&nbsp;0&nbsp;||&nbsp;r.end_line&nbsp;&lt;&nbsp;r.start_line&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r.end_line&nbsp;&gt;=&nbsp;static_cast&lt;int&gt;(lines.size()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;replace-cpp-method:&nbsp;invalid&nbsp;region&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;begin&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;r.start_line;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;end&nbsp;&nbsp;&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;(r.end_line&nbsp;+&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;prefix&nbsp;=&nbsp;extract_indent_prefix(lines,&nbsp;r.start_line);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;payload&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;apply_indent_prefix(s.payload,&nbsp;prefix,&nbsp;s.indent_from_marker);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.erase(begin,&nbsp;end);<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.insert(lines.begin()&nbsp;+&nbsp;r.start_line,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.begin(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.end());<br>
}<br>
<br>
void&nbsp;replace_py_class(const&nbsp;Section&nbsp;&amp;s,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;filepath,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;text,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(s.arg1.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-py-class:&nbsp;missing&nbsp;class&nbsp;name&nbsp;for&nbsp;file:&nbsp;&quot;&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filepath);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(text);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!finder.find_class(s.arg1,&nbsp;r))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-py-class:&nbsp;class&nbsp;not&nbsp;found:&nbsp;&quot;&nbsp;+&nbsp;s.arg1&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;in&nbsp;file:&nbsp;&quot;&nbsp;+&nbsp;filepath);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(r.start_line&nbsp;&lt;&nbsp;0&nbsp;||&nbsp;r.end_line&nbsp;&lt;&nbsp;r.start_line&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r.end_line&nbsp;&gt;=&nbsp;static_cast&lt;int&gt;(lines.size()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;replace-py-class:&nbsp;invalid&nbsp;region&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;begin&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;r.start_line;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;end&nbsp;&nbsp;&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;(r.end_line&nbsp;+&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;prefix&nbsp;=&nbsp;extract_indent_prefix(lines,&nbsp;r.start_line);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;payload&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;apply_indent_prefix(s.payload,&nbsp;prefix,&nbsp;s.indent_from_marker);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.erase(begin,&nbsp;end);<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.insert(lines.begin()&nbsp;+&nbsp;r.start_line,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.begin(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.end());<br>
}<br>
<br>
void&nbsp;replace_py_method(const&nbsp;Section&nbsp;&amp;s,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;filepath,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;text,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;[cls,&nbsp;method]&nbsp;=&nbsp;parse_python_target(s);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;PythonSymbolFinder&nbsp;finder(text);<br>
&nbsp;&nbsp;&nbsp;&nbsp;Region&nbsp;r;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!finder.find_method(cls,&nbsp;method,&nbsp;r))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;replace-py-method:&nbsp;method&nbsp;not&nbsp;found:&nbsp;&quot;&nbsp;+&nbsp;cls&nbsp;+&nbsp;&quot;.&quot;&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;method&nbsp;+&nbsp;&quot;&nbsp;in&nbsp;file:&nbsp;&quot;&nbsp;+&nbsp;filepath);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(r.start_line&nbsp;&lt;&nbsp;0&nbsp;||&nbsp;r.end_line&nbsp;&lt;&nbsp;r.start_line&nbsp;||<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r.end_line&nbsp;&gt;=&nbsp;static_cast&lt;int&gt;(lines.size()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;replace-py-method:&nbsp;invalid&nbsp;region&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;begin&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;r.start_line;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;end&nbsp;&nbsp;&nbsp;=&nbsp;lines.begin()&nbsp;+&nbsp;(r.end_line&nbsp;+&nbsp;1);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;prefix&nbsp;=&nbsp;extract_indent_prefix(lines,&nbsp;r.start_line);<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;payload&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;apply_indent_prefix(s.payload,&nbsp;prefix,&nbsp;s.indent_from_marker);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.erase(begin,&nbsp;end);<br>
&nbsp;&nbsp;&nbsp;&nbsp;lines.insert(lines.begin()&nbsp;+&nbsp;r.start_line,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.begin(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;payload.end());<br>
}<br>
}&nbsp;//&nbsp;namespace<br>
<br>
void&nbsp;apply_symbol_commands(const&nbsp;std::string&nbsp;&amp;filepath,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;&amp;lines,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::vector&lt;const&nbsp;Section&nbsp;*&gt;&nbsp;&amp;sections)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;Section&nbsp;*s&nbsp;:&nbsp;sections)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;text&nbsp;=&nbsp;join_lines(lines);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(s-&gt;command&nbsp;==&nbsp;&quot;replace-cpp-class&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replace_cpp_class(*s,&nbsp;filepath,&nbsp;text,&nbsp;lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(s-&gt;command&nbsp;==&nbsp;&quot;replace-cpp-method&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replace_cpp_method(*s,&nbsp;filepath,&nbsp;text,&nbsp;lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(s-&gt;command&nbsp;==&nbsp;&quot;replace-py-class&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replace_py_class(*s,&nbsp;filepath,&nbsp;text,&nbsp;lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(s-&gt;command&nbsp;==&nbsp;&quot;replace-py-method&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;replace_py_method(*s,&nbsp;filepath,&nbsp;text,&nbsp;lines);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;apply_symbol_commands:&nbsp;unknown&nbsp;command:&nbsp;&quot;&nbsp;+&nbsp;s-&gt;command);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
