<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/symbol_command_objects.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#pragma&nbsp;once<br>
<br>
#include&nbsp;&quot;section.h&quot;<br>
#include&nbsp;&quot;symbols.h&quot;<br>
<br>
#include&nbsp;&lt;functional&gt;<br>
#include&nbsp;&lt;memory&gt;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;vector&gt;<br>
<br>
namespace&nbsp;symbol_commands_detail<br>
{<br>
class&nbsp;SymbolCommand<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;~SymbolCommand()&nbsp;=&nbsp;default;<br>
&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;void&nbsp;execute(std::vector&lt;std::string&gt;&nbsp;&amp;lines)&nbsp;=&nbsp;0;<br>
};<br>
<br>
class&nbsp;RegionReplaceCommand&nbsp;:&nbsp;public&nbsp;SymbolCommand<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;RegionReplaceCommand(const&nbsp;Section&nbsp;&amp;s,&nbsp;std::string&nbsp;path);<br>
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;execute(std::vector&lt;std::string&gt;&nbsp;&amp;lines)&nbsp;override;<br>
<br>
protected:<br>
&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;bool&nbsp;find_region(const&nbsp;std::string&nbsp;&amp;text,&nbsp;Region&nbsp;&amp;r)&nbsp;const&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;std::string&nbsp;not_found_error()&nbsp;const&nbsp;=&nbsp;0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;virtual&nbsp;std::string&nbsp;invalid_region_error()&nbsp;const&nbsp;=&nbsp;0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;Section&nbsp;&amp;section;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;filepath;<br>
};<br>
<br>
class&nbsp;ReplaceCppClassCommand&nbsp;:&nbsp;public&nbsp;RegionReplaceCommand<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;ReplaceCppClassCommand(const&nbsp;Section&nbsp;&amp;s,&nbsp;std::string&nbsp;path);<br>
<br>
protected:<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_region(const&nbsp;std::string&nbsp;&amp;text,&nbsp;Region&nbsp;&amp;r)&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;not_found_error()&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;invalid_region_error()&nbsp;const&nbsp;override;<br>
};<br>
<br>
class&nbsp;ReplaceCppMethodCommand&nbsp;:&nbsp;public&nbsp;RegionReplaceCommand<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;ReplaceCppMethodCommand(const&nbsp;Section&nbsp;&amp;s,&nbsp;std::string&nbsp;path);<br>
<br>
protected:<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_region(const&nbsp;std::string&nbsp;&amp;text,&nbsp;Region&nbsp;&amp;r)&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;not_found_error()&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;invalid_region_error()&nbsp;const&nbsp;override;<br>
<br>
private:<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;cls;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;method;<br>
};<br>
<br>
class&nbsp;ReplacePyClassCommand&nbsp;:&nbsp;public&nbsp;RegionReplaceCommand<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;ReplacePyClassCommand(const&nbsp;Section&nbsp;&amp;s,&nbsp;std::string&nbsp;path);<br>
<br>
protected:<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_region(const&nbsp;std::string&nbsp;&amp;text,&nbsp;Region&nbsp;&amp;r)&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;not_found_error()&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;invalid_region_error()&nbsp;const&nbsp;override;<br>
};<br>
<br>
class&nbsp;ReplacePyMethodCommand&nbsp;:&nbsp;public&nbsp;RegionReplaceCommand<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;ReplacePyMethodCommand(const&nbsp;Section&nbsp;&amp;s,&nbsp;std::string&nbsp;path);<br>
<br>
protected:<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;find_region(const&nbsp;std::string&nbsp;&amp;text,&nbsp;Region&nbsp;&amp;r)&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;not_found_error()&nbsp;const&nbsp;override;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;invalid_region_error()&nbsp;const&nbsp;override;<br>
<br>
private:<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;cls;<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;method;<br>
};<br>
<br>
using&nbsp;SymbolCommandFactory&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::function&lt;std::unique_ptr&lt;SymbolCommand&gt;(const&nbsp;Section&nbsp;&amp;,&nbsp;const&nbsp;std::string&nbsp;&amp;)&gt;;<br>
}&nbsp;//&nbsp;namespace&nbsp;symbol_commands_detail<br>
<!-- END SCAT CODE -->
</body>
</html>
