<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/guard/env.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
//&nbsp;guard/check/env.h<br>
#pragma&nbsp;once<br>
<br>
#include&nbsp;&lt;exception&gt;<br>
#include&nbsp;&lt;string&gt;<br>
<br>
//&nbsp;Вся&nbsp;среда&nbsp;проверки&nbsp;в&nbsp;одной&nbsp;структуре<br>
struct&nbsp;guard_check_env_t<br>
{<br>
std::string&nbsp;error_msg;<br>
unsigned&nbsp;long&nbsp;long&nbsp;assert_total&nbsp;=&nbsp;0;<br>
unsigned&nbsp;long&nbsp;long&nbsp;assert_failed&nbsp;=&nbsp;0;<br>
};<br>
<br>
//&nbsp;Глобальный&nbsp;(на&nbsp;процесс)&nbsp;экземпляр&nbsp;среды,&nbsp;реализованный&nbsp;через<br>
//&nbsp;статическую&nbsp;локальную&nbsp;переменную&nbsp;внутри&nbsp;inline-функции<br>
inline&nbsp;guard_check_env_t&nbsp;&amp;guard_check_env()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;guard_check_env_t&nbsp;env;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;env;<br>
}<br>
<br>
//&nbsp;Макросы-алиасы,&nbsp;чтобы&nbsp;старый&nbsp;код&nbsp;продолжал&nbsp;работать&nbsp;как&nbsp;раньше<br>
#define&nbsp;guard_check_error_msg&nbsp;(guard_check_env().error_msg)<br>
<br>
//&nbsp;Начало&nbsp;&quot;окружения&quot;&nbsp;проверки:&nbsp;очищаем&nbsp;строку&nbsp;и&nbsp;запускаем&nbsp;try-блок<br>
#define&nbsp;GUARD_CHECK_ENV_START()&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(guard_check_error_msg.clear(),&nbsp;true)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try<br>
<br>
//&nbsp;Ветка&nbsp;обработки&nbsp;ошибки&nbsp;(после&nbsp;выброса&nbsp;guard_check_exception)<br>
#define&nbsp;GUARD_CHECK_ENV_ERROR_HANDLER()&nbsp;catch&nbsp;(const&nbsp;guard_check_exception&nbsp;&amp;)<br>
<br>
//&nbsp;Установка&nbsp;сообщения&nbsp;об&nbsp;ошибке&nbsp;(перезаписывает&nbsp;предыдущий&nbsp;текст)<br>
inline&nbsp;void&nbsp;GUARD_CHECK_ENV_RAISE_SET(const&nbsp;std::string&nbsp;&amp;msg)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;guard_check_error_msg&nbsp;=&nbsp;msg;<br>
}<br>
<br>
//&nbsp;Переход&nbsp;назад&nbsp;в&nbsp;точку&nbsp;GUARD_CHECK_ENV_START()<br>
class&nbsp;guard_check_exception&nbsp;:&nbsp;public&nbsp;std::exception<br>
{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*what()&nbsp;const&nbsp;noexcept&nbsp;override<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;guard&nbsp;test&nbsp;failure&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
};<br>
inline&nbsp;void&nbsp;GUARD_CHECK_ENV_RAISE_IMPL()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;guard_check_exception{};<br>
}<br>
inline&nbsp;void&nbsp;GUARD_CHECK_ENV_COUNT_ASSERT(bool&nbsp;success)<br>
{<br>
guard_check_env_t&nbsp;&amp;env&nbsp;=&nbsp;guard_check_env();<br>
++env.assert_total;<br>
if&nbsp;(!success)<br>
&nbsp;&nbsp;&nbsp;&nbsp;++env.assert_failed;<br>
}<br>
<br>
//&nbsp;Добавление&nbsp;сообщения&nbsp;об&nbsp;ошибке&nbsp;(для&nbsp;&quot;мягких&quot;&nbsp;CHECK)<br>
inline&nbsp;void&nbsp;GUARD_CHECK_ENV_APPEND(const&nbsp;std::string&nbsp;&amp;msg)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!guard_check_error_msg.empty())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;guard_check_error_msg.push_back('\n');<br>
&nbsp;&nbsp;&nbsp;&nbsp;guard_check_error_msg&nbsp;+=&nbsp;msg;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
