<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/guard/util.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#pragma&nbsp;once<br>
<br>
#include&nbsp;&lt;cmath&gt;<br>
#include&nbsp;&lt;limits&gt;<br>
#include&nbsp;&lt;ostream&gt;<br>
<br>
namespace&nbsp;guard&nbsp;{<br>
<br>
class&nbsp;Approx&nbsp;{<br>
public:<br>
&nbsp;&nbsp;&nbsp;&nbsp;explicit&nbsp;Approx(double&nbsp;value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;m_value(value),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_epsilon(1e-12),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_scale(1.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Задать&nbsp;относительную&nbsp;погрешность<br>
&nbsp;&nbsp;&nbsp;&nbsp;Approx&amp;&nbsp;epsilon(double&nbsp;eps)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_epsilon&nbsp;=&nbsp;eps;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Задать&nbsp;масштаб&nbsp;(как&nbsp;в&nbsp;doctest&nbsp;/&nbsp;Catch2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;Approx&amp;&nbsp;scale(double&nbsp;s)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_scale&nbsp;=&nbsp;s;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Чтобы&nbsp;можно&nbsp;было&nbsp;использовать&nbsp;готовый&nbsp;Approx&nbsp;как&nbsp;&quot;шаблон&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;auto&nbsp;a&nbsp;=&nbsp;Approx::custom().epsilon(1e-3).scale(10.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;&nbsp;&nbsp;CHECK(x&nbsp;==&nbsp;a(5.0));<br>
&nbsp;&nbsp;&nbsp;&nbsp;Approx&nbsp;operator()(double&nbsp;value)&nbsp;const&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Approx&nbsp;copy&nbsp;=&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;copy.m_value&nbsp;=&nbsp;value;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;copy;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;value()&nbsp;const&nbsp;&nbsp;&nbsp;{&nbsp;return&nbsp;m_value;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;epsilon()&nbsp;const&nbsp;{&nbsp;return&nbsp;m_epsilon;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;scale()&nbsp;const&nbsp;&nbsp;&nbsp;{&nbsp;return&nbsp;m_scale;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Для&nbsp;отладочных&nbsp;сообщений<br>
&nbsp;&nbsp;&nbsp;&nbsp;friend&nbsp;std::ostream&amp;&nbsp;operator&lt;&lt;(std::ostream&amp;&nbsp;os,&nbsp;const&nbsp;Approx&amp;&nbsp;a)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os&nbsp;&lt;&lt;&nbsp;&quot;Approx(&quot;&nbsp;&lt;&lt;&nbsp;a.m_value<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;&lt;&nbsp;&quot;,&nbsp;eps=&quot;&nbsp;&lt;&lt;&nbsp;a.m_epsilon<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;&lt;&nbsp;&quot;,&nbsp;scale=&quot;&nbsp;&lt;&lt;&nbsp;a.m_scale&nbsp;&lt;&lt;&nbsp;&quot;)&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;os;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Сравнение&nbsp;&quot;число&nbsp;==&nbsp;Approx(...)&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;friend&nbsp;bool&nbsp;operator==(double&nbsp;lhs,&nbsp;const&nbsp;Approx&amp;&nbsp;rhs)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;rhs.compare(lhs);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;friend&nbsp;bool&nbsp;operator==(const&nbsp;Approx&amp;&nbsp;lhs,&nbsp;double&nbsp;rhs)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;lhs.compare(rhs);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;friend&nbsp;bool&nbsp;operator!=(double&nbsp;lhs,&nbsp;const&nbsp;Approx&amp;&nbsp;rhs)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;!rhs.compare(lhs);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;friend&nbsp;bool&nbsp;operator!=(const&nbsp;Approx&amp;&nbsp;lhs,&nbsp;double&nbsp;rhs)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;!lhs.compare(rhs);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
private:<br>
&nbsp;&nbsp;&nbsp;&nbsp;bool&nbsp;compare(double&nbsp;other)&nbsp;const&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;double&nbsp;diff&nbsp;=&nbsp;std::fabs(other&nbsp;-&nbsp;m_value);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;double&nbsp;tolerance&nbsp;=&nbsp;m_epsilon&nbsp;*&nbsp;(m_scale&nbsp;+&nbsp;std::fabs(m_value));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;diff&nbsp;&lt;=&nbsp;tolerance;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;m_value;<br>
&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;m_epsilon;<br>
&nbsp;&nbsp;&nbsp;&nbsp;double&nbsp;m_scale;<br>
};<br>
<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
