<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/yaml/access.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;IGRIS_UTIL_ACCESS_H&#13;
#define&nbsp;IGRIS_UTIL_ACCESS_H&#13;
&#13;
#include&nbsp;&lt;stdint.h&gt;&#13;
&#13;
//#ifndef&nbsp;_MSC_VER&#13;
//#include&nbsp;&quot;endian.h&quot;&#13;
//#endif&#13;
&#13;
static&nbsp;inline&nbsp;uint8_t&nbsp;HIHALF(uint8_t&nbsp;byte)&nbsp;{&nbsp;return&nbsp;(byte&nbsp;&gt;&gt;&nbsp;4)&nbsp;&amp;&nbsp;0x0F;&nbsp;}&#13;
static&nbsp;inline&nbsp;uint8_t&nbsp;LOHALF(uint8_t&nbsp;byte)&nbsp;{&nbsp;return&nbsp;byte&nbsp;&amp;&nbsp;0x0F;&nbsp;}&#13;
&#13;
//#ifndef&nbsp;BYTE_ORDER&#13;
//#	define&nbsp;BYTE_ORDER&nbsp;__LITTLE_ENDIAN&#13;
//#endif&#13;
&#13;
#if&nbsp;__BYTE_ORDER__&nbsp;==&nbsp;__ORDER_BIG_ENDIAN__&#13;
&#13;
#define&nbsp;INT16_HI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)&#13;
#define&nbsp;INT16_LO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)&#13;
&#13;
#define&nbsp;INT32_HHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)&#13;
#define&nbsp;INT32_HLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)&#13;
#define&nbsp;INT32_LHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)&#13;
#define&nbsp;INT32_LLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)&#13;
&#13;
#define&nbsp;INT64_HHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)&#13;
#define&nbsp;INT64_HHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)&#13;
#define&nbsp;INT64_HLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)&#13;
#define&nbsp;INT64_HLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)&#13;
#define&nbsp;INT64_LHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;4)&#13;
#define&nbsp;INT64_LHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;5)&#13;
#define&nbsp;INT64_LLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;6)&#13;
#define&nbsp;INT64_LLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;7)&#13;
&#13;
#elif&nbsp;__BYTE_ORDER__&nbsp;==&nbsp;__ORDER_LITTLE_ENDIAN__&#13;
&#13;
#define&nbsp;INT16_HI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)&#13;
#define&nbsp;INT16_LO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)&#13;
&#13;
#define&nbsp;INT32_HHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)&#13;
#define&nbsp;INT32_HLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)&#13;
#define&nbsp;INT32_LHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)&#13;
#define&nbsp;INT32_LLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)&#13;
&#13;
#define&nbsp;INT64_HHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;7)&#13;
#define&nbsp;INT64_HHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;6)&#13;
#define&nbsp;INT64_HLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;5)&#13;
#define&nbsp;INT64_HLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;4)&#13;
#define&nbsp;INT64_LHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)&#13;
#define&nbsp;INT64_LHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)&#13;
#define&nbsp;INT64_LLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)&#13;
#define&nbsp;INT64_LLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)&#13;
&#13;
#endif&#13;
&#13;
#define&nbsp;UINT16_HI(arg)&nbsp;INT16_HI(arg)&#13;
#define&nbsp;UINT16_LO(arg)&nbsp;INT16_LO(arg)&#13;
&#13;
#define&nbsp;UINT32_HHI(arg)&nbsp;INT32_HHI(arg)&#13;
#define&nbsp;UINT32_HLO(arg)&nbsp;INT32_HLO(arg)&#13;
#define&nbsp;UINT32_LHI(arg)&nbsp;INT32_LHI(arg)&#13;
#define&nbsp;UINT32_LLO(arg)&nbsp;INT32_LLO(arg)&#13;
&#13;
#define&nbsp;UINT64_HHHI(arg)&nbsp;INT64_HHHI(arg)&#13;
#define&nbsp;UINT64_HHLO(arg)&nbsp;INT64_HHLO(arg)&#13;
#define&nbsp;UINT64_HLHI(arg)&nbsp;INT64_HLHI(arg)&#13;
#define&nbsp;UINT64_HLLO(arg)&nbsp;INT64_HLLO(arg)&#13;
#define&nbsp;UINT64_LHHI(arg)&nbsp;INT64_LHHI(arg)&#13;
#define&nbsp;UINT64_LHLO(arg)&nbsp;INT64_LHLO(arg)&#13;
#define&nbsp;UINT64_LLHI(arg)&nbsp;INT64_LLHI(arg)&#13;
#define&nbsp;UINT64_LLLO(arg)&nbsp;INT64_LLLO(arg)&#13;
&#13;
#endif&nbsp;//&nbsp;GENOS_UTIL_ACCESS_H&#13;
<!-- END SCAT CODE -->
</body>
</html>
