<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/yaml/access.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;IGRIS_UTIL_ACCESS_H<br>
#define&nbsp;IGRIS_UTIL_ACCESS_H<br>
<br>
#include&nbsp;&lt;stdint.h&gt;<br>
<br>
//#ifndef&nbsp;_MSC_VER<br>
//#include&nbsp;&quot;endian.h&quot;<br>
//#endif<br>
<br>
static&nbsp;inline&nbsp;uint8_t&nbsp;HIHALF(uint8_t&nbsp;byte)&nbsp;{&nbsp;return&nbsp;(byte&nbsp;&gt;&gt;&nbsp;4)&nbsp;&amp;&nbsp;0x0F;&nbsp;}<br>
static&nbsp;inline&nbsp;uint8_t&nbsp;LOHALF(uint8_t&nbsp;byte)&nbsp;{&nbsp;return&nbsp;byte&nbsp;&amp;&nbsp;0x0F;&nbsp;}<br>
<br>
//#ifndef&nbsp;BYTE_ORDER<br>
//#	define&nbsp;BYTE_ORDER&nbsp;__LITTLE_ENDIAN<br>
//#endif<br>
<br>
#if&nbsp;__BYTE_ORDER__&nbsp;==&nbsp;__ORDER_BIG_ENDIAN__<br>
<br>
#define&nbsp;INT16_HI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)<br>
#define&nbsp;INT16_LO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)<br>
<br>
#define&nbsp;INT32_HHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)<br>
#define&nbsp;INT32_HLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)<br>
#define&nbsp;INT32_LHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)<br>
#define&nbsp;INT32_LLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)<br>
<br>
#define&nbsp;INT64_HHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)<br>
#define&nbsp;INT64_HHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)<br>
#define&nbsp;INT64_HLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)<br>
#define&nbsp;INT64_HLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)<br>
#define&nbsp;INT64_LHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;4)<br>
#define&nbsp;INT64_LHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;5)<br>
#define&nbsp;INT64_LLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;6)<br>
#define&nbsp;INT64_LLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;7)<br>
<br>
#elif&nbsp;__BYTE_ORDER__&nbsp;==&nbsp;__ORDER_LITTLE_ENDIAN__<br>
<br>
#define&nbsp;INT16_HI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)<br>
#define&nbsp;INT16_LO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)<br>
<br>
#define&nbsp;INT32_HHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)<br>
#define&nbsp;INT32_HLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)<br>
#define&nbsp;INT32_LHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)<br>
#define&nbsp;INT32_LLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)<br>
<br>
#define&nbsp;INT64_HHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;7)<br>
#define&nbsp;INT64_HHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;6)<br>
#define&nbsp;INT64_HLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;5)<br>
#define&nbsp;INT64_HLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;4)<br>
#define&nbsp;INT64_LHHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;3)<br>
#define&nbsp;INT64_LHLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;2)<br>
#define&nbsp;INT64_LLHI(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;1)<br>
#define&nbsp;INT64_LLLO(arg)&nbsp;*((uint8_t&nbsp;*)&amp;arg&nbsp;+&nbsp;0)<br>
<br>
#endif<br>
<br>
#define&nbsp;UINT16_HI(arg)&nbsp;INT16_HI(arg)<br>
#define&nbsp;UINT16_LO(arg)&nbsp;INT16_LO(arg)<br>
<br>
#define&nbsp;UINT32_HHI(arg)&nbsp;INT32_HHI(arg)<br>
#define&nbsp;UINT32_HLO(arg)&nbsp;INT32_HLO(arg)<br>
#define&nbsp;UINT32_LHI(arg)&nbsp;INT32_LHI(arg)<br>
#define&nbsp;UINT32_LLO(arg)&nbsp;INT32_LLO(arg)<br>
<br>
#define&nbsp;UINT64_HHHI(arg)&nbsp;INT64_HHHI(arg)<br>
#define&nbsp;UINT64_HHLO(arg)&nbsp;INT64_HHLO(arg)<br>
#define&nbsp;UINT64_HLHI(arg)&nbsp;INT64_HLHI(arg)<br>
#define&nbsp;UINT64_HLLO(arg)&nbsp;INT64_HLLO(arg)<br>
#define&nbsp;UINT64_LHHI(arg)&nbsp;INT64_LHHI(arg)<br>
#define&nbsp;UINT64_LHLO(arg)&nbsp;INT64_LHLO(arg)<br>
#define&nbsp;UINT64_LLHI(arg)&nbsp;INT64_LLHI(arg)<br>
#define&nbsp;UINT64_LLLO(arg)&nbsp;INT64_LLLO(arg)<br>
<br>
#endif&nbsp;//&nbsp;GENOS_UTIL_ACCESS_H<br>
<!-- END SCAT CODE -->
</body>
</html>
