<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/yaml/ctrdtr.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;NOS_UTIL_CTRDTR_H&#13;
#define&nbsp;NOS_UTIL_CTRDTR_H&#13;
&#13;
#include&nbsp;&lt;new&gt;&#13;
&#13;
namespace&nbsp;nos&#13;
{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;typename&nbsp;T&gt;&nbsp;void&nbsp;destructor(T&nbsp;*ptr)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ptr-&gt;~T();&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;typename&nbsp;T,&nbsp;typename...&nbsp;Args&gt;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;constructor(T&nbsp;*ptr,&nbsp;Args&nbsp;&amp;&amp;...&nbsp;args)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new&nbsp;((void&nbsp;*)ptr)&nbsp;T(std::forward&lt;Args&gt;(args)...);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;typename&nbsp;T&gt;&nbsp;void&nbsp;copy_constructor(T&nbsp;*ptr,&nbsp;const&nbsp;T&nbsp;&amp;other)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new&nbsp;((void&nbsp;*)ptr)&nbsp;T(other);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;typename&nbsp;T&gt;&nbsp;void&nbsp;move_constructor(T&nbsp;*ptr,&nbsp;T&nbsp;&amp;&amp;other)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new&nbsp;((void&nbsp;*)ptr)&nbsp;T(std::move(other));&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;class&nbsp;InputIterator,&nbsp;class&nbsp;EndIterator&gt;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;array_destructor(InputIterator&nbsp;first,&nbsp;EndIterator&nbsp;last)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(first&nbsp;!=&nbsp;last)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::destructor(&amp;*first);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++first;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;template&nbsp;&lt;class&nbsp;InputIterator,&nbsp;class&nbsp;EndIterator,&nbsp;typename...&nbsp;Args&gt;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;void&nbsp;array_constructor(InputIterator&nbsp;first,&nbsp;EndIterator&nbsp;last,&nbsp;Args...&nbsp;args)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;(first&nbsp;!=&nbsp;last)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;*first,&nbsp;args...);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++first;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
}&#13;
&#13;
#endif&#13;
<!-- END SCAT CODE -->
</body>
</html>
