<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/yaml/hexascii.h</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#ifndef&nbsp;NOS_UTIL_HEXASCII_H<br>
#define&nbsp;NOS_UTIL_HEXASCII_H<br>
<br>
/**<br>
@file<br>
*/<br>
<br>
#include&nbsp;&quot;access.h&quot;<br>
#include&nbsp;&lt;stdint.h&gt;<br>
<br>
/*__BEGIN_DECLS<br>
<br>
void&nbsp;hexascii_encode(const&nbsp;void&nbsp;*indata,&nbsp;int&nbsp;size,&nbsp;void&nbsp;*out);<br>
void&nbsp;hexascii_decode(const&nbsp;void&nbsp;*indata,&nbsp;int&nbsp;size,&nbsp;void&nbsp;*out);<br>
<br>
__END_DECLS*/<br>
<br>
constexpr&nbsp;static&nbsp;inline&nbsp;uint8_t&nbsp;hex2half(char&nbsp;c)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(uint8_t)(c&nbsp;&lt;=&nbsp;'9'&nbsp;?&nbsp;c&nbsp;-&nbsp;'0'&nbsp;:&nbsp;c&nbsp;-&nbsp;'A'&nbsp;+&nbsp;10);<br>
}<br>
<br>
constexpr&nbsp;static&nbsp;inline&nbsp;char&nbsp;half2hex(uint8_t&nbsp;n)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(char)(n&nbsp;&lt;&nbsp;10&nbsp;?&nbsp;'0'&nbsp;+&nbsp;n&nbsp;:&nbsp;'A'&nbsp;-&nbsp;10&nbsp;+&nbsp;n);<br>
}<br>
<br>
constexpr&nbsp;static&nbsp;inline&nbsp;uint8_t&nbsp;hex2byte(char&nbsp;hi,&nbsp;char&nbsp;lo)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(uint8_t)((hex2half(hi)&nbsp;&lt;&lt;&nbsp;4)&nbsp;+&nbsp;hex2half(lo));<br>
}<br>
<br>
static&nbsp;inline&nbsp;uint8_t&nbsp;hex_to_uint8(const&nbsp;char&nbsp;*hex)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint8_t&nbsp;out;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;out&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;0),&nbsp;*(hex&nbsp;+&nbsp;1));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
}<br>
<br>
static&nbsp;inline&nbsp;uint16_t&nbsp;hex_to_uint16(const&nbsp;char&nbsp;*hex)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint16_t&nbsp;out;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT16_HI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;0),&nbsp;*(hex&nbsp;+&nbsp;1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT16_LO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;2),&nbsp;*(hex&nbsp;+&nbsp;3));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
}<br>
<br>
static&nbsp;inline&nbsp;uint32_t&nbsp;hex_to_uint32(const&nbsp;char&nbsp;*hex)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint32_t&nbsp;out;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT32_HHI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;0),&nbsp;*(hex&nbsp;+&nbsp;1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT32_HLO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;2),&nbsp;*(hex&nbsp;+&nbsp;3));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT32_LHI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;4),&nbsp;*(hex&nbsp;+&nbsp;5));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT32_LLO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;6),&nbsp;*(hex&nbsp;+&nbsp;7));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
}<br>
<br>
static&nbsp;inline&nbsp;uint64_t&nbsp;hex_to_uint64(const&nbsp;char&nbsp;*hex)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;uint64_t&nbsp;out;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_HHHI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;0),&nbsp;*(hex&nbsp;+&nbsp;1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_HHLO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;2),&nbsp;*(hex&nbsp;+&nbsp;3));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_HLHI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;4),&nbsp;*(hex&nbsp;+&nbsp;5));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_HLLO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;6),&nbsp;*(hex&nbsp;+&nbsp;7));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_LHHI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;8),&nbsp;*(hex&nbsp;+&nbsp;9));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_LHLO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;10),&nbsp;*(hex&nbsp;+&nbsp;11));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_LLHI(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;12),&nbsp;*(hex&nbsp;+&nbsp;13));<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT64_LLLO(out)&nbsp;=&nbsp;hex2byte(*(hex&nbsp;+&nbsp;14),&nbsp;*(hex&nbsp;+&nbsp;15));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;out;<br>
}<br>
<br>
static&nbsp;inline&nbsp;void&nbsp;uint8_to_hex(char&nbsp;*hex,&nbsp;uint8_t&nbsp;in)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(in));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(in));<br>
}<br>
<br>
static&nbsp;inline&nbsp;void&nbsp;uint16_to_hex(char&nbsp;*hex,&nbsp;uint16_t&nbsp;in)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT16_HI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT16_HI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT16_LO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT16_LO(in)));<br>
}<br>
<br>
static&nbsp;inline&nbsp;void&nbsp;uint32_to_hex(char&nbsp;*hex,&nbsp;uint32_t&nbsp;in)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT32_HHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT32_HHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT32_HLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT32_HLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT32_LHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT32_LHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT32_LLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT32_LLO(in)));<br>
}<br>
<br>
static&nbsp;inline&nbsp;void&nbsp;uint64_to_hex(char&nbsp;*hex,&nbsp;uint64_t&nbsp;in)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_HHHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_HHHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_HHLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_HHLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_HLHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_HLHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_HLLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_HLLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_LHHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_LHHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_LHLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_LHLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_LLHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_LLHI(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(HIHALF(UINT64_LLLO(in)));<br>
&nbsp;&nbsp;&nbsp;&nbsp;*hex++&nbsp;=&nbsp;half2hex(LOHALF(UINT64_LLLO(in)));<br>
}<br>
<br>
#endif<br>
<!-- END SCAT CODE -->
</body>
</html>
