<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>src/yaml/trent.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;trent.h&quot;<br>
#include&nbsp;&quot;trent_path.h&quot;<br>
<br>
const&nbsp;char&nbsp;*nos::typestr(nos::trent_type&nbsp;m_type)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;nos::trent_type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;str&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;nos::trent_type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;list&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;nos::trent_type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;dict&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;nos::trent_type::numer:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;num&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;nos::trent_type::boolean:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;bool&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;nos::trent_type::nil:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;nil&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;&quot;;<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::static_nil()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;const&nbsp;trent&nbsp;_nil;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_nil;<br>
}<br>
<br>
nos::trent::wrong_path::wrong_path(const&nbsp;nos::trent_path&nbsp;&amp;path)&nbsp;:&nbsp;path(path)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;=&nbsp;std::string(&quot;trent:wrong_path:&nbsp;&quot;)&nbsp;+&nbsp;path.to_string();<br>
}<br>
<br>
const&nbsp;char&nbsp;*nos::trent::wrong_path::what()&nbsp;const&nbsp;noexcept<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;str.c_str();<br>
}<br>
<br>
nos::trent::wrong_type::wrong_type(const&nbsp;trent_path&nbsp;&amp;path,&nbsp;type&nbsp;t,&nbsp;type&nbsp;rt)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;path(path),&nbsp;t(t)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;=&nbsp;std::string(&quot;trent:wrong_type:&quot;)&nbsp;+&nbsp;std::string(&quot;&nbsp;path:&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path.to_string()&nbsp;+&nbsp;std::string(&quot;&nbsp;request:&quot;)&nbsp;+&nbsp;nos::typestr(t)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string(&quot;&nbsp;realtype:&quot;)&nbsp;+&nbsp;nos::typestr(rt);<br>
}<br>
<br>
const&nbsp;char&nbsp;*nos::trent::wrong_type::what()&nbsp;const&nbsp;noexcept<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;str.c_str();<br>
}<br>
<br>
nos::trent::wrong_index::wrong_index(const&nbsp;trent_path&nbsp;&amp;path,&nbsp;type&nbsp;t)<br>
&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;path(path),&nbsp;t(t)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;str&nbsp;=&nbsp;std::string(&quot;trent:wrong_index:&nbsp;path:&nbsp;&quot;)&nbsp;+&nbsp;path.to_string()&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string(&quot;&nbsp;index:&nbsp;&quot;)&nbsp;+&nbsp;nos::typestr(t);<br>
}<br>
<br>
const&nbsp;char&nbsp;*nos::trent::wrong_index::what()&nbsp;const&nbsp;noexcept<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;str.c_str();<br>
}<br>
<br>
const&nbsp;char&nbsp;*nos::trent::typestr()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::typestr(m_type);<br>
}<br>
<br>
nos::trent::~trent()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;invalidate();<br>
}<br>
<br>
nos::trent::trent()&nbsp;:&nbsp;m_type(type::nil)&nbsp;{}<br>
<br>
nos::trent::trent(const&nbsp;trent&nbsp;&amp;other)&nbsp;:&nbsp;m_type(other.m_type)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_str,&nbsp;other.m_str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_arr,&nbsp;other.m_arr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_dct,&nbsp;other.m_dct);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::numer:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;other.m_num;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::boolean:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_bool&nbsp;=&nbsp;other.m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::nil:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
nos::trent::trent(trent&nbsp;&amp;&amp;other)&nbsp;noexcept&nbsp;:&nbsp;m_type(other.m_type)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::move_constructor(&amp;m_str,&nbsp;std::move(other.m_str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::move_constructor(&amp;m_arr,&nbsp;std::move(other.m_arr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::move_constructor(&amp;m_dct,&nbsp;std::move(other.m_dct));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::numer:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;other.m_num;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::boolean:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_bool&nbsp;=&nbsp;other.m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::nil:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;other.invalidate();<br>
}<br>
<br>
void&nbsp;nos::trent::invalidate()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::destructor(&amp;m_str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::destructor(&amp;m_arr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::destructor(&amp;m_dct);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;type::nil;<br>
}<br>
<br>
void&nbsp;nos::trent::init_sint(const&nbsp;int64_t&nbsp;&amp;i)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;type::numer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;static_cast&lt;numer_type&gt;(i);<br>
}<br>
<br>
void&nbsp;nos::trent::init_uint(const&nbsp;uint64_t&nbsp;&amp;i)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;type::numer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;i;<br>
}<br>
<br>
void&nbsp;nos::trent::init_flt(const&nbsp;long&nbsp;double&nbsp;&amp;i)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;type::numer;<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;i;<br>
}<br>
<br>
void&nbsp;nos::trent::init_str(const&nbsp;char&nbsp;*data,&nbsp;size_t&nbsp;size)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;type::string;<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_str,&nbsp;data,&nbsp;size);<br>
}<br>
<br>
void&nbsp;nos::trent::init(trent::type&nbsp;t)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;trent::type::nil)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;invalidate();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;t;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_arr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;trent::type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_dct);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;default:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
nos::trent&nbsp;&amp;nos::trent::operator[](int&nbsp;i)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_arr.size()&nbsp;&lt;=&nbsp;(unsigned&nbsp;int)i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_arr.resize(i&nbsp;+&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr[i];<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;char&nbsp;*key)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::dict);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct[std::string(key)];<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;std::string&nbsp;&amp;key)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::dict);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct[key];<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;nos::buffer&nbsp;&amp;key)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::dict);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct[std::string(key.data(),&nbsp;key.size())];<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;std::string&nbsp;&amp;obj)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict&nbsp;||&nbsp;!contains(obj))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;static_nil();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;at(obj);<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;nos::buffer&nbsp;&amp;obj)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;key(obj.data(),&nbsp;obj.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict&nbsp;||&nbsp;!contains(key))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;static_nil();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;at(key);<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;char&nbsp;*obj)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict&nbsp;||&nbsp;!contains(obj))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;static_nil();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;at(obj);<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::operator[](int&nbsp;obj)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;static_nil();<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;at(obj);<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;p&nbsp;:&nbsp;path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(p.is_string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;tr-&gt;at(p.str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;tr-&gt;at(p.i32);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*tr;<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::operator[](const&nbsp;trent_path&nbsp;&amp;path)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;p&nbsp;:&nbsp;path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(p.is_string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;((*tr)[p.str]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;((*tr)[p.i32]);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*tr;<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::at(const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;p&nbsp;:&nbsp;path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(p.is_string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;tr-&gt;at(p.str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;tr-&gt;at(p.i32);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*tr;<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::at(const&nbsp;trent_path&nbsp;&amp;path)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;p&nbsp;:&nbsp;path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(p.is_string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;tr-&gt;at(p.str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;&amp;tr-&gt;at(p.i32);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*tr;<br>
}<br>
<br>
bool&nbsp;nos::trent::contains(const&nbsp;char&nbsp;*key)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct.find(key)&nbsp;!=&nbsp;m_dct.end();<br>
}<br>
<br>
bool&nbsp;nos::trent::contains(std::string&nbsp;key)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;false;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct.find(std::string(key))&nbsp;!=&nbsp;m_dct.end();<br>
}<br>
<br>
void&nbsp;nos::trent::init_from_list(const&nbsp;std::initializer_list&lt;double&gt;&nbsp;l)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;init(type::list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_arr.reserve(l.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;i&nbsp;:&nbsp;l)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_arr.emplace_back(i);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
void&nbsp;nos::trent::init_from_list(const&nbsp;std::initializer_list&lt;std::string&gt;&nbsp;l)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;init(type::list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_arr.reserve(l.size());<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;i&nbsp;:&nbsp;l)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_arr.emplace_back(i);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::at(int&nbsp;i)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;list:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_arr.size()&nbsp;&lt;=&nbsp;(unsigned&nbsp;int)i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:wrong_index:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::to_string(i));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr[i];<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::at(int&nbsp;i)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;list:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_arr.size()&nbsp;&lt;=&nbsp;(unsigned&nbsp;int)i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:wrong_index:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::to_string(i));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr[i];<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::at(const&nbsp;std::string&nbsp;&amp;key)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;dict:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct.at(key);<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::at(const&nbsp;std::string&nbsp;&amp;key)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;dict:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct.at(key);<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::at(const&nbsp;char&nbsp;*key)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;dict:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct.at(std::string(key));<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::at(const&nbsp;char&nbsp;*key)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::dict)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;dict:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct.at(std::string(key));<br>
}<br>
<br>
void&nbsp;nos::trent::push_back(const&nbsp;trent&nbsp;&amp;tr)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(m_type&nbsp;!=&nbsp;type::list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_arr.push_back(tr);<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;*nos::trent::_get(const&nbsp;std::string&nbsp;&amp;str)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;it&nbsp;=&nbsp;m_dct.find(str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(it&nbsp;==&nbsp;m_dct.end())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&amp;it-&gt;second;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;*nos::trent::_get(const&nbsp;char&nbsp;*str)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;get(std::string(str));<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;*nos::trent::_get(int&nbsp;index)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&amp;m_arr[index];<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;*nos::trent::get(const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(const&nbsp;auto&nbsp;&amp;p&nbsp;:&nbsp;path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(p.is_string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!tr-&gt;is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;tr-&gt;_get(p.str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;tr-&gt;_get(p.i32);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nullptr;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr;<br>
}<br>
<br>
const&nbsp;nos::trent&nbsp;&amp;nos::trent::get_except(const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;get(path);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr&nbsp;==&nbsp;nullptr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;wrong_path(path);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*tr;<br>
}<br>
nos::trent::numer_type<br>
nos::trent::get_as_numer_ex(const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;&amp;tr&nbsp;=&nbsp;get_except(path);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr.m_type&nbsp;!=&nbsp;trent_type::numer)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;wrong_type(path,&nbsp;trent_type::numer,&nbsp;tr.m_type);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr.m_num;<br>
}<br>
<br>
const&nbsp;nos::trent::string_type&nbsp;&amp;<br>
nos::trent::get_as_string_ex(const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;&amp;tr&nbsp;=&nbsp;get_except(path);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr.m_type&nbsp;!=&nbsp;trent_type::string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;wrong_type(path,&nbsp;trent_type::string,&nbsp;tr.m_type);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr.m_str;<br>
}<br>
<br>
bool&nbsp;nos::trent::get_as_boolean_ex(const&nbsp;trent_path&nbsp;&amp;path)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;&amp;tr&nbsp;=&nbsp;get_except(path);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr.m_type&nbsp;!=&nbsp;trent_type::boolean)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;wrong_type(path,&nbsp;trent_type::boolean,&nbsp;tr.m_type);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr.m_bool;<br>
}<br>
<br>
nos::trent::numer_type<br>
nos::trent::get_as_numer_def(const&nbsp;trent_path&nbsp;&amp;path,&nbsp;numer_type&nbsp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;get(path);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr&nbsp;==&nbsp;nullptr&nbsp;||&nbsp;tr-&gt;m_type&nbsp;!=&nbsp;trent_type::numer)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;def;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr-&gt;m_num;<br>
}<br>
<br>
const&nbsp;nos::trent::string_type&nbsp;&amp;<br>
nos::trent::get_as_string_def(const&nbsp;trent_path&nbsp;&amp;path,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;std::string&nbsp;&amp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;get(path);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr&nbsp;==&nbsp;nullptr&nbsp;||&nbsp;tr-&gt;m_type&nbsp;!=&nbsp;trent_type::string)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;def;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr-&gt;m_str;<br>
}<br>
<br>
bool&nbsp;nos::trent::get_as_boolean_def(const&nbsp;trent_path&nbsp;&amp;path,&nbsp;bool&nbsp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;trent&nbsp;*tr&nbsp;=&nbsp;get(path);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(tr&nbsp;==&nbsp;nullptr&nbsp;||&nbsp;tr-&gt;m_type&nbsp;!=&nbsp;trent_type::boolean)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;def;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr-&gt;m_bool;<br>
}<br>
<br>
nos::trent::string_type&nbsp;&amp;nos::trent::as_string()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::string);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
const&nbsp;nos::trent::string_type&nbsp;&amp;nos::trent::as_string()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(std::string(&quot;trent:&nbsp;is&nbsp;not&nbsp;a&nbsp;string:&nbsp;&quot;)&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::typestr(m_type));<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
nos::expected&lt;nos::trent::string_type&nbsp;&amp;,&nbsp;nos::errstring&gt;<br>
nos::trent::as_string_critical()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;string&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
nos::expected&lt;const&nbsp;nos::trent::string_type&nbsp;&amp;,&nbsp;nos::errstring&gt;<br>
nos::trent::as_string_critical()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;string&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
nos::trent::string_type&nbsp;&amp;nos::trent::as_string_except()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;isn't&nbsp;string&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
const&nbsp;nos::trent::string_type&nbsp;&amp;nos::trent::as_string_except()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;isn't&nbsp;string&quot;);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
const&nbsp;nos::trent::string_type&nbsp;&amp;<br>
nos::trent::as_string_default(const&nbsp;string_type&nbsp;&amp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;def;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
nos::trent::dict_type&nbsp;&amp;nos::trent::as_dict()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::dict);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
const&nbsp;nos::trent::dict_type&nbsp;&amp;nos::trent::as_dict()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;dict&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
nos::expected&lt;nos::trent::dict_type&nbsp;&amp;,&nbsp;nos::errstring&gt;<br>
nos::trent::as_dict_critical()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
nos::expected&lt;const&nbsp;nos::trent::dict_type&nbsp;&amp;,&nbsp;nos::errstring&gt;<br>
nos::trent::as_dict_critical()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
nos::trent::dict_type&nbsp;&amp;nos::trent::as_dict_except()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
const&nbsp;nos::trent::dict_type&nbsp;&amp;nos::trent::as_dict_except()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_dict())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
nos::trent::list_type&nbsp;&amp;nos::trent::as_list()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;init(type::list);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
const&nbsp;nos::trent::list_type&nbsp;&amp;nos::trent::as_list()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
nos::expected&lt;nos::trent::list_type&nbsp;&amp;,&nbsp;nos::errstring&gt;<br>
nos::trent::as_list_critical()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
nos::expected&lt;const&nbsp;nos::trent::list_type&nbsp;&amp;,&nbsp;nos::errstring&gt;<br>
nos::trent::as_list_critical()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
nos::trent::list_type&nbsp;&amp;nos::trent::as_list_except()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
const&nbsp;nos::trent::list_type&nbsp;&amp;nos::trent::as_list_except()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_list())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;list&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
nos::trent::numer_type&nbsp;nos::trent::as_numer()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(int)m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;std::stod(m_str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;numer&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
nos::trent::integer_type&nbsp;nos::trent::as_integer()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(int)m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;numer&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
nos::expected&lt;nos::trent::numer_type,&nbsp;nos::errstring&gt;<br>
nos::trent::as_numer_critical()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(int)m_bool;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;numer&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
nos::trent::numer_type&nbsp;nos::trent::as_numer_except()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(int)m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;numer&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
nos::trent::numer_type&nbsp;nos::trent::as_numer_default(numer_type&nbsp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(int)m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;def;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
int64_t&nbsp;nos::trent::as_integer_default(int64_t&nbsp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;as_numer_default(def);<br>
}<br>
<br>
nos::expected&lt;int64_t,&nbsp;nos::errstring&gt;<br>
nos::trent::as_integer_critical()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;numer&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
int64_t&nbsp;nos::trent::as_integer_except()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_numer())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;numer&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
bool&nbsp;nos::trent::as_bool()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_bool;<br>
}<br>
<br>
bool&nbsp;nos::trent::as_bool_default(bool&nbsp;def)&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;def;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_bool;<br>
}<br>
<br>
nos::expected&lt;bool,&nbsp;nos::errstring&gt;&nbsp;nos::trent::as_bool_critical()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;errstring(&quot;is't&nbsp;bool&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_bool;<br>
}<br>
<br>
bool&nbsp;nos::trent::as_bool_except()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_bool())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;bool&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_bool;<br>
}<br>
<br>
const&nbsp;nos::buffer&nbsp;nos::trent::as_buffer()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!is_string())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;std::runtime_error(&quot;is't&nbsp;string&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;nos::buffer(m_str.data(),&nbsp;m_str.size());<br>
}<br>
<br>
nos::trent::numer_type&nbsp;&amp;nos::trent::unsafe_numer_const()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
nos::trent::string_type&nbsp;&amp;nos::trent::unsafe_string_const()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
nos::trent::list_type&nbsp;&amp;nos::trent::unsafe_list_const()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
nos::trent::dict_type&nbsp;&amp;nos::trent::unsafe_dict_const()<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
const&nbsp;nos::trent::numer_type&nbsp;&amp;nos::trent::unsafe_numer_const()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_num;<br>
}<br>
<br>
const&nbsp;nos::trent::string_type&nbsp;&amp;nos::trent::unsafe_string_const()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_str;<br>
}<br>
<br>
const&nbsp;nos::trent::list_type&nbsp;&amp;nos::trent::unsafe_list_const()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_arr;<br>
}<br>
<br>
const&nbsp;nos::trent::dict_type&nbsp;&amp;nos::trent::unsafe_dict_const()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_dct;<br>
}<br>
<br>
const&nbsp;bool&nbsp;&amp;nos::trent::unsafe_bool_const()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_bool;<br>
}<br>
<br>
nos::trent::type&nbsp;nos::trent::get_type()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type;<br>
}<br>
<br>
bool&nbsp;nos::trent::is_nil()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type&nbsp;==&nbsp;type::nil;<br>
}<br>
<br>
bool&nbsp;nos::trent::is_bool()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type&nbsp;==&nbsp;type::boolean;<br>
}<br>
<br>
bool&nbsp;nos::trent::is_numer()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type&nbsp;==&nbsp;type::numer;<br>
}<br>
<br>
bool&nbsp;nos::trent::is_list()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type&nbsp;==&nbsp;type::list;<br>
}<br>
<br>
bool&nbsp;nos::trent::is_dict()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type&nbsp;==&nbsp;type::dict;<br>
}<br>
<br>
bool&nbsp;nos::trent::is_string()&nbsp;const<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m_type&nbsp;==&nbsp;type::string;<br>
}<br>
nos::trent&nbsp;&amp;nos::trent::operator=(const&nbsp;trent&nbsp;&amp;other)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(this&nbsp;==&nbsp;&amp;other)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;invalidate();<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;other.m_type;<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_str,&nbsp;other.m_str);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_arr,&nbsp;other.m_arr);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::constructor(&amp;m_dct,&nbsp;other.m_dct);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::numer:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;other.m_num;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::boolean:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_bool&nbsp;=&nbsp;other.m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::nil:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
}<br>
<br>
nos::trent&nbsp;&amp;nos::trent::operator=(trent&nbsp;&amp;&amp;other)&nbsp;noexcept<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(this&nbsp;==&nbsp;&amp;other)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;invalidate();<br>
&nbsp;&nbsp;&nbsp;&nbsp;m_type&nbsp;=&nbsp;other.m_type;<br>
&nbsp;&nbsp;&nbsp;&nbsp;switch&nbsp;(m_type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::string:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::move_constructor(&amp;m_str,&nbsp;std::move(other.m_str));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::move_constructor(&amp;m_arr,&nbsp;std::move(other.m_arr));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nos::move_constructor(&amp;m_dct,&nbsp;std::move(other.m_dct));<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::numer:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_num&nbsp;=&nbsp;other.m_num;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::boolean:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;m_bool&nbsp;=&nbsp;other.m_bool;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;case&nbsp;type::nil:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;other.reset(type::nil);<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;*this;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
