<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/main.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#define&nbsp;DOCTEST_CONFIG_IMPLEMENT&#13;
#include&nbsp;&quot;doctest/doctest.h&quot;&#13;
#include&nbsp;&lt;string&gt;&#13;
#include&nbsp;&lt;vector&gt;&#13;
#if&nbsp;defined(__WIN32__)&nbsp;||&nbsp;defined(_MSC_VER)&#13;
#include&nbsp;&lt;winsock2.h&gt;&#13;
WSADATA&nbsp;wsaData;&#13;
#endif&#13;
&#13;
int&nbsp;main(int&nbsp;argc,&nbsp;char&nbsp;**argv)&#13;
{&#13;
#if&nbsp;defined(__WIN32__)&nbsp;||&nbsp;defined(_MSC_VER)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;iResult;&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Initialize&nbsp;Winsock&#13;
&nbsp;&nbsp;&nbsp;&nbsp;iResult&nbsp;=&nbsp;WSAStartup(MAKEWORD(2,&nbsp;2),&nbsp;&amp;wsaData);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(iResult&nbsp;!=&nbsp;0)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(&quot;WSAStartup&nbsp;failed:&nbsp;%d\n&quot;,&nbsp;iResult);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;1;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
#endif&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;std::string&gt;&nbsp;adjusted_args;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;adjusted_args.reserve(argc);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0;&nbsp;i&nbsp;&lt;&nbsp;argc;&nbsp;++i)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;current(argv[i]);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;((current&nbsp;==&nbsp;&quot;--test-case&quot;&nbsp;||&nbsp;current&nbsp;==&nbsp;&quot;-tc&quot;)&nbsp;&amp;&amp;&nbsp;i&nbsp;+&nbsp;1&nbsp;&lt;&nbsp;argc)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string&nbsp;pattern(argv[i&nbsp;+&nbsp;1]);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(pattern.find('*')&nbsp;==&nbsp;std::string::npos)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pattern&nbsp;=&nbsp;&quot;*&quot;&nbsp;+&nbsp;pattern&nbsp;+&nbsp;&quot;*&quot;;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;adjusted_args.push_back(current&nbsp;+&nbsp;&quot;=&quot;&nbsp;+&nbsp;pattern);&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;++i;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;adjusted_args.push_back(std::move(current));&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;std::vector&lt;char&nbsp;*&gt;&nbsp;argv_adjusted;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;argv_adjusted.reserve(adjusted_args.size());&#13;
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(auto&nbsp;&amp;arg&nbsp;:&nbsp;adjusted_args)&#13;
&nbsp;&nbsp;&nbsp;&nbsp;{&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;argv_adjusted.push_back(arg.data());&#13;
&nbsp;&nbsp;&nbsp;&nbsp;}&#13;
&#13;
&nbsp;&nbsp;&nbsp;&nbsp;doctest::Context&nbsp;context;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;context.applyCommandLine(static_cast&lt;int&gt;(argv_adjusted.size()),&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;argv_adjusted.data());&#13;
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;res&nbsp;=&nbsp;context.run();&nbsp;&nbsp;//&nbsp;run&#13;
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(context.shouldExit())&nbsp;//&nbsp;important&nbsp;-&nbsp;query&nbsp;flags&nbsp;(and&nbsp;--exit)&nbsp;rely&nbsp;on&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;the&nbsp;user&nbsp;doing&nbsp;this&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;res;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;propagate&nbsp;the&nbsp;result&nbsp;of&nbsp;the&nbsp;tests&#13;
&nbsp;&nbsp;&nbsp;&nbsp;int&nbsp;client_stuff_return_code&nbsp;=&nbsp;0;&#13;
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;res&nbsp;+&nbsp;client_stuff_return_code;&nbsp;//&nbsp;the&nbsp;result&nbsp;from&nbsp;doctest&nbsp;is&#13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;propagated&nbsp;here&nbsp;as&nbsp;well&#13;
}&#13;
<!-- END SCAT CODE -->
</body>
</html>
