<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/yaml_parser.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;doctest/doctest.h&quot;<br>
#include&nbsp;&lt;yaml/yaml.h&gt;<br>
#include&nbsp;&lt;cmath&gt;<br>
#include&nbsp;&lt;string&gt;<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;reads&nbsp;flow&nbsp;collections&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;flow:&nbsp;[1,&nbsp;2,&nbsp;{foo:&nbsp;true,&nbsp;bar:&nbsp;[alpha,&nbsp;beta]}]\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;flow&nbsp;=&nbsp;dict.at(&quot;flow&quot;).as_list();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(flow.size()&nbsp;==&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(flow[0].as_numer()&nbsp;==&nbsp;doctest::Approx(1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(flow[1].as_numer()&nbsp;==&nbsp;doctest::Approx(2));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;map&nbsp;=&nbsp;flow[2].as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(map.at(&quot;foo&quot;).as_bool()&nbsp;==&nbsp;true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;inner&nbsp;=&nbsp;map.at(&quot;bar&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(inner.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(inner[0].as_string()&nbsp;==&nbsp;&quot;alpha&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(inner[1].as_string()&nbsp;==&nbsp;&quot;beta&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;handles&nbsp;block&nbsp;scalars&nbsp;and&nbsp;folding&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;literal:&nbsp;|\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;line1\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;line2\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;folded:&nbsp;&gt;-\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;a\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;b\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;c\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;literal&quot;).as_string()&nbsp;==&nbsp;&quot;line1\nline2\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;folded&quot;).as_string()&nbsp;==&nbsp;&quot;a&nbsp;b\nc&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;understands&nbsp;YAML&nbsp;1.2&nbsp;scalars&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v1:&nbsp;1_000\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v2:&nbsp;.inf\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v3:&nbsp;-.inf\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v4:&nbsp;.nan\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;v1&quot;).as_numer()&nbsp;==&nbsp;doctest::Approx(1000));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::isinf(dict.at(&quot;v2&quot;).as_numer()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;v3&quot;).as_numer()&nbsp;&lt;&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::isnan(dict.at(&quot;v4&quot;).as_numer()));<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;reports&nbsp;flow&nbsp;errors&nbsp;with&nbsp;location&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=&nbsp;&quot;flow:&nbsp;[1,&nbsp;2\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void)nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FAIL(&quot;parse&nbsp;must&nbsp;throw&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;nos::yaml::parse_error&nbsp;&amp;err)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(err.line()&nbsp;==&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(err.column()&nbsp;!=&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::string(err.what()).find(&quot;unterminated&nbsp;flow&quot;)&nbsp;!=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string::npos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
