<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>tests/yaml_parser.cpp</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#include&nbsp;&quot;doctest/doctest.h&quot;<br>
#include&nbsp;&lt;yaml/yaml.h&gt;<br>
#include&nbsp;&lt;cmath&gt;<br>
#include&nbsp;&lt;limits&gt;<br>
#include&nbsp;&lt;string&gt;<br>
#include&nbsp;&lt;stdexcept&gt;<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;reads&nbsp;flow&nbsp;collections&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;flow:&nbsp;[1,&nbsp;2,&nbsp;{foo:&nbsp;true,&nbsp;bar:&nbsp;[alpha,&nbsp;beta]}]\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;flow&nbsp;=&nbsp;dict.at(&quot;flow&quot;).as_list();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(flow.size()&nbsp;==&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(flow[0].as_numer()&nbsp;==&nbsp;doctest::Approx(1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(flow[1].as_numer()&nbsp;==&nbsp;doctest::Approx(2));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;map&nbsp;=&nbsp;flow[2].as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(map.at(&quot;foo&quot;).as_bool()&nbsp;==&nbsp;true);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;inner&nbsp;=&nbsp;map.at(&quot;bar&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(inner.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(inner[0].as_string()&nbsp;==&nbsp;&quot;alpha&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(inner[1].as_string()&nbsp;==&nbsp;&quot;beta&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;handles&nbsp;block&nbsp;scalars&nbsp;and&nbsp;folding&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;literal:&nbsp;|\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;line1\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;line2\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;folded:&nbsp;&gt;-\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;a\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;b\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;c\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;literal&quot;).as_string()&nbsp;==&nbsp;&quot;line1\nline2\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;folded&quot;).as_string()&nbsp;==&nbsp;&quot;a&nbsp;b\nc&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;understands&nbsp;YAML&nbsp;1.2&nbsp;scalars&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v1:&nbsp;1_000\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v2:&nbsp;.inf\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v3:&nbsp;-.inf\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;v4:&nbsp;.nan\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;v1&quot;).as_numer()&nbsp;==&nbsp;doctest::Approx(1000));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::isinf(dict.at(&quot;v2&quot;).as_numer()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;v3&quot;).as_numer()&nbsp;&lt;&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::isnan(dict.at(&quot;v4&quot;).as_numer()));<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;reports&nbsp;flow&nbsp;errors&nbsp;with&nbsp;location&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=&nbsp;&quot;flow:&nbsp;[1,&nbsp;2\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void)nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FAIL(&quot;parse&nbsp;must&nbsp;throw&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;nos::yaml::parse_error&nbsp;&amp;err)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(err.line()&nbsp;==&nbsp;1);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(err.column()&nbsp;!=&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::string(err.what()).find(&quot;unterminated&nbsp;flow&quot;)&nbsp;!=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;std::string::npos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;handles&nbsp;document&nbsp;markers&nbsp;and&nbsp;comments&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;---\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;name:&nbsp;test&nbsp;#&nbsp;comment\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;list:&nbsp;[a,&nbsp;b]&nbsp;#&nbsp;trailing\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;...\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;nos::trent&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;dict&nbsp;=&nbsp;root.as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;name&quot;).as_string()&nbsp;==&nbsp;&quot;test&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;list&nbsp;=&nbsp;dict.at(&quot;list&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(list.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(list[0].as_string()&nbsp;==&nbsp;&quot;a&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(list[1].as_string()&nbsp;==&nbsp;&quot;b&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;respects&nbsp;quoted&nbsp;scalars&nbsp;and&nbsp;escapes&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;double:&nbsp;\&quot;line\\nwith\\\\slash\\\&quot;quote\\u0041\&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;single:&nbsp;'it''s&nbsp;fine'\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;colon:&nbsp;\&quot;a:&nbsp;b\&quot;\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(root.at(&quot;double&quot;).as_string()&nbsp;==&nbsp;&quot;line\nwith\\slash\&quot;quoteA&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(root.at(&quot;single&quot;).as_string()&nbsp;==&nbsp;&quot;it's&nbsp;fine&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(root.at(&quot;colon&quot;).as_string()&nbsp;==&nbsp;&quot;a:&nbsp;b&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;handles&nbsp;flow&nbsp;collections&nbsp;across&nbsp;lines&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;flow:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;[1,\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;2,\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;{key:&nbsp;[10,\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;20]}]\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;flow&nbsp;=&nbsp;root.at(&quot;flow&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(flow.size()&nbsp;==&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(flow[2].as_dict().at(&quot;key&quot;).as_list().at(1).as_numer()&nbsp;==<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;doctest::Approx(20));<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;handles&nbsp;literal,&nbsp;folded&nbsp;and&nbsp;chomping&nbsp;styles&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;literal:&nbsp;|+\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;one\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;two\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;folded:&nbsp;&gt;-\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;a\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;b\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;c\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;strip:&nbsp;|-\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;keep\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;text\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;literal&quot;).as_string()&nbsp;==&nbsp;&quot;one\ntwo\n\n&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;folded&quot;).as_string()&nbsp;==&nbsp;&quot;a&nbsp;b\nc&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;strip&quot;).as_string()&nbsp;==&nbsp;&quot;keep\ntext&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;recognizes&nbsp;YAML&nbsp;1.2&nbsp;numeric/boolean/null&nbsp;forms&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;u:&nbsp;1_234_567\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;pinf:&nbsp;+.inf\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;ninf:&nbsp;-.inf\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;nanv:&nbsp;.nan\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;nulls:&nbsp;[null,&nbsp;~]\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;bools:&nbsp;[TRUE,&nbsp;false]\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;u&quot;).as_numer()&nbsp;==&nbsp;doctest::Approx(1234567));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::isinf(dict.at(&quot;pinf&quot;).as_numer()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;ninf&quot;).as_numer()&nbsp;&lt;&nbsp;0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(std::isnan(dict.at(&quot;nanv&quot;).as_numer()));<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;nulls&nbsp;=&nbsp;dict.at(&quot;nulls&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(nulls[0].is_nil());<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(nulls[1].is_nil());<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;bools&nbsp;=&nbsp;dict.at(&quot;bools&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(bools[0].as_bool());<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_FALSE(bools[1].as_bool());<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;treats&nbsp;colon&nbsp;without&nbsp;whitespace&nbsp;as&nbsp;plain&nbsp;scalar&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;text:&nbsp;foo:bar\n&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;text&quot;).as_string()&nbsp;==&nbsp;&quot;foo:bar&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;errors&nbsp;on&nbsp;bad&nbsp;indentation&nbsp;with&nbsp;location&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;a:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-&nbsp;1\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;-&nbsp;2\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_THROWS_AS(nos::yaml::parse(src),&nbsp;nos::yaml::parse_error);<br>
&nbsp;&nbsp;&nbsp;&nbsp;try<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(void)nos::yaml::parse(src);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;catch&nbsp;(const&nbsp;nos::yaml::parse_error&nbsp;&amp;err)<br>
&nbsp;&nbsp;&nbsp;&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHECK(err.line()&nbsp;==&nbsp;3);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;errors&nbsp;on&nbsp;empty&nbsp;keys&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=&nbsp;&quot;:&nbsp;value\n&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK_THROWS_AS(nos::yaml::parse(src),&nbsp;nos::yaml::parse_error);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;handles&nbsp;nested&nbsp;sequences&nbsp;and&nbsp;mappings&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;root:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-&nbsp;name:&nbsp;item1\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;values:&nbsp;[1,&nbsp;2,&nbsp;3]\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-&nbsp;name:&nbsp;item2\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;details:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enabled:&nbsp;true\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tags:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;x\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;y\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;root&nbsp;=&nbsp;nos::yaml::parse(src).as_dict().at(&quot;root&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(root.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(root[0].as_dict().at(&quot;values&quot;).as_list().at(2).as_numer()&nbsp;==<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;doctest::Approx(3));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(root[1].as_dict()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.at(&quot;details&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.as_dict()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.at(&quot;tags&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.as_list()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.at(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.as_string()&nbsp;==&nbsp;&quot;y&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;supports&nbsp;flow&nbsp;map&nbsp;values&nbsp;on&nbsp;mapping&nbsp;lines&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;cfg:&nbsp;{a:&nbsp;1,&nbsp;b:&nbsp;[2,&nbsp;3]}\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;cfg&nbsp;=&nbsp;nos::yaml::parse(src).as_dict().at(&quot;cfg&quot;).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(cfg.at(&quot;a&quot;).as_numer()&nbsp;==&nbsp;doctest::Approx(1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;arr&nbsp;=&nbsp;cfg.at(&quot;b&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(arr.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(arr[1].as_numer()&nbsp;==&nbsp;doctest::Approx(3));<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;honors&nbsp;empty&nbsp;block&nbsp;scalar&nbsp;when&nbsp;indent&nbsp;inferred&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;k:&nbsp;|\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;line\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;;<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;k&quot;).as_string()&nbsp;==&nbsp;&quot;line\n&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;allows&nbsp;blank&nbsp;lines&nbsp;between&nbsp;mapping&nbsp;entries&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;a:&nbsp;1\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;b:&nbsp;2\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(dict.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;a&quot;).as_numer()&nbsp;==&nbsp;doctest::Approx(1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;b&quot;).as_numer()&nbsp;==&nbsp;doctest::Approx(2));<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;allows&nbsp;comments&nbsp;and&nbsp;blank&nbsp;lines&nbsp;between&nbsp;mapping&nbsp;entries&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;first:&nbsp;one\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;#&nbsp;comment&nbsp;between&nbsp;keys\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;&nbsp;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;second:&nbsp;two\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(dict.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;first&quot;).as_string()&nbsp;==&nbsp;&quot;one&quot;);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(dict.at(&quot;second&quot;).as_string()&nbsp;==&nbsp;&quot;two&quot;);<br>
}<br>
<br>
TEST_CASE(&quot;YAML&nbsp;parser&nbsp;allows&nbsp;blank&nbsp;lines&nbsp;inside&nbsp;sequences&quot;)<br>
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;char&nbsp;*src&nbsp;=<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;list:\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-&nbsp;1\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;\n&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&nbsp;&nbsp;-&nbsp;2\n&quot;;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;dict&nbsp;=&nbsp;nos::yaml::parse(src).as_dict();<br>
&nbsp;&nbsp;&nbsp;&nbsp;auto&nbsp;&amp;list&nbsp;=&nbsp;dict.at(&quot;list&quot;).as_list();<br>
&nbsp;&nbsp;&nbsp;&nbsp;REQUIRE(list.size()&nbsp;==&nbsp;2);<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(list[0].as_numer()&nbsp;==&nbsp;doctest::Approx(1));<br>
&nbsp;&nbsp;&nbsp;&nbsp;CHECK(list[1].as_numer()&nbsp;==&nbsp;doctest::Approx(2));<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
